# default .prettierrc or .prettierrc.yaml
# trailingComma: "es5"
# tabWidth: 4
# semi: false
# singleQuote: true

printWidth: 100
tabWidth: 2
# useTabs: true
semi: false
singleQuote: true
jsxSingleQuote: true
trailingComma: all
# bracketSpacing: true
# bracketSameLine: true
arrowParens: avoid
htmlWhitespaceSensitivity: ignore

